AWSTemplateFormatVersion : "2010-09-09"
Description : "Creates S3 buckte | Join"

Parameters :
  S3BucketName:
    Description : Enter S3 Bucket Name
    Type : String
    MinLength : 3
    MaxLength : 10
    AllowedValues : "[A-Za-z]+"

Resources :
  S3Bucket:
    Type : AWS::S3::Bucket
    Properties :
      BucketName : !Join ['-', [!Ref S3BucketName, !Ref AWS::Region, !Ref AWS::StackName]]

