AWSTemplateFormatVersion : "2010-09-09"
Description : "Create EC2 instance"

Parameters:
  Environment:
    Type : String
    Allowed Values:
      -dev
      -prod
      -qa

Mappings:
  EnvMap: #Logical id/name
    dev:
      instanceType : "t2.large"
      name : "dev"

    qa:
      instanceType : "t2.medium"
      name : "qa"

    prod:
      instanceType : "t2.xlarge"
      name : "prod"

Conditions :
  CreateProdResources : !Equals [!Ref Environment, prod]

Resources:
  Instance: #logical id/name
    Type : AWS::EC2::Instance
    Properties :
      InstanceType : !FindMap[EnvMap, !Ref Environment, instanceType]

      ImageId : ami-0dba2cb6798deb6d8
      Tags :
        -key : "Name"
        -Value : !FindInMap[EnvMap, !Ref Environment, name]

  MountPoint:
    Type : AWS::EC2::VolumeAttachment
    Condition : CreateProdResources # to reference conditions just write the name of the conditions, no need to use the !Ref and all those stuff
    Properties:
      InstanceId:
        !Ref Instance
      VolumeId:
        !Ref NewVolume
      Device : /dev/sdh

  NewVolume:
    Type : AWS::EC2::Volume
    Condition : CreateProdResources
    Properties: 
      size: 100 #GBs is the unit
      AvalibilityZone:
        !GetAtt Instance.AvailibilityZone

Outputs:
  InstanceName:
    Value : !Ref Instance

