AWSTemplateFormatVersion : "2010-09-09"
Description : "Create EC2 Instance"

Parameters :
  Environment :
    Type : String
    AllowedValues :
      -dev
      -prod
      -qa

Mappings :
  EnvMap : 
    dev :
      instanceType : "t2.large"
      name : "dev"

    qa :
      instanceType : "t2.medium"
      name : "qa"

    prod :
      instanceType : "t2.xlarge"
      name : "prod"

Resources:
  Instance : 
    Type : AWS::EC2::Instance
    Properties:
      InstanceType : !FindMap [EnvMap, !Ref Environment, instanceType]
      ImageId : ami-0dba2cb6798deb6d8
      Tags:
        -key : "Name"
         Value : !FindMap [EnvMap, !Ref Environment, Name]

Outputs :
  InstanceName:
    Value : !Ref Instance
