################ Original CF Template ####################

AWSTemplateFormatVersion : "2010-09-09"
Description : "ChangeSet"

Parameters :
  S3BucketName:
    Description : Enter S3 Bucket Name
    Type : String

Resources :
  S3Bucket : 
  Type : AWS::S3::Bucket
  Properties:
    BucketName : !Ref S3BucketName

Outputs:
  BucketName:
    value : !Ref 'S3Bucket'

####################### Now modifiying the CF template ############################

AWSTemplateFormatVersion : "2010-09-09"
Description : "ChangeSet"

Parameters :
  S3BucketName:
    Description : Enter S3 Bucket Name
    Type : String

  InstanceTypeParameter:
    Description : Select instance type
    Type : String
    Default : t2.micro
    AllowedValues :
      -t2.micro
      -t2.small
      -t2.large
    Description : Enter t2.micro, t2.small, t2.large. Default is t2.micro

Resources :
  S3Bucket :
  Type : AWS::S3::Bucket
  Properties:
    BucketName : !Ref S3BucketName

  Instance :
    Type : AWS::EC2::Instance
    Properties :
      InstanceType : !Ref InstanceTypeParameter
      ImageId : ami-0dba2cb6798deb6d8


Outputs:
  BucketName:
    value : !Ref 'S3Bucket'

